### PR TITLE
fix: reboot dialog

### PR DESCRIPTION
**Pull request by holly79**
Canceling the restart dialog had no effect and the host was restarted anyway. The restart dialog has been moved to a function and canceling the restart dialog now leads to calling the main dialog.

### CODE REVIEW

**Comment by h3xp** [comment]
Nice PR, we are currently discussing this. We might not allow cancellation because some updates require it to take effect and rebooting only costs a couple of seconds and might get rid of some "bug" reports we are getting. I'll leave this open for now until a decision is made.

In that case we would remove or rename the "Cancel" button.

**Comment by holly79** [comment]
Let me know if I should  change something

**Comment by h3xp** [comment]
Could you change the message to "Reboot required for these changes to take effect. Rebooting now.", so it is clear that we strongly recommend to reboot but still let the user cancel it if he/she insists?

**Comment by holly79** [comment]
Changed the messages :-)

**Pull request merged**
